export const DragTypes = {
  PLAYER: 'Player',
};

export const ActionTypes = {
  DRAG_PIP: 'DRAG_PIP',
  TOGGLE_POSITIONS: 'TOGGLE_POSITIONS',
  ENABLE_RESIZE: 'ENABLE_RESIZE',
  RESIZE_PIP: 'RESIZE_PIP',
  END_RESIZE_PIP: 'END_RESIZE_PIP',
  RESIZE_CHAT: 'RESIZE_CHAT',
  SWITCH_CHAT: 'SWITCH_CHAT',
  ADD_PLAYER: 'ADD_PLAYER',
  CLOSE_PLAYER: 'CLOSE_PLAYER',
};
